// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdVowmwh2BC8GSKXLSf6JpMeAIcyUmOGM',
    appId: '1:705787553792:web:95ee810d9b70a3e95350e5',
    messagingSenderId: '705787553792',
    projectId: 'pizza-delivery-7eb8b',
    authDomain: 'pizza-delivery-7eb8b.firebaseapp.com',
    storageBucket: 'pizza-delivery-7eb8b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOOd7dJHNgqoVkaDI1RVoS9fUoFHX6LW4',
    appId: '1:705787553792:android:7001ba7322ae71605350e5',
    messagingSenderId: '705787553792',
    projectId: 'pizza-delivery-7eb8b',
    storageBucket: 'pizza-delivery-7eb8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGdLqrjoyXs0CGHapi-baUyV5iuzzgIY0',
    appId: '1:705787553792:ios:ee6d35fdf457c5315350e5',
    messagingSenderId: '705787553792',
    projectId: 'pizza-delivery-7eb8b',
    storageBucket: 'pizza-delivery-7eb8b.appspot.com',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGdLqrjoyXs0CGHapi-baUyV5iuzzgIY0',
    appId: '1:705787553792:ios:ee6d35fdf457c5315350e5',
    messagingSenderId: '705787553792',
    projectId: 'pizza-delivery-7eb8b',
    storageBucket: 'pizza-delivery-7eb8b.appspot.com',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdVowmwh2BC8GSKXLSf6JpMeAIcyUmOGM',
    appId: '1:705787553792:web:5e2b394b309472275350e5',
    messagingSenderId: '705787553792',
    projectId: 'pizza-delivery-7eb8b',
    authDomain: 'pizza-delivery-7eb8b.firebaseapp.com',
    storageBucket: 'pizza-delivery-7eb8b.appspot.com',
  );
}
