// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdwfArySXBpzWAokh4IGINnJ_GOoIEBXI',
    appId: '1:396159394257:android:97f4972301a260162fc0f0',
    messagingSenderId: '396159394257',
    projectId: 'hakim-learning-flutter',
    storageBucket: 'hakim-learning-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRU_G-ESwjyDxkMK1PzJLKTCpwyyc1r6Q',
    appId: '1:396159394257:ios:4dc0afc79893d3942fc0f0',
    messagingSenderId: '396159394257',
    projectId: 'hakim-learning-flutter',
    storageBucket: 'hakim-learning-flutter.appspot.com',
    iosBundleId: 'com.example.learningDart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRU_G-ESwjyDxkMK1PzJLKTCpwyyc1r6Q',
    appId: '1:396159394257:ios:4dc0afc79893d3942fc0f0',
    messagingSenderId: '396159394257',
    projectId: 'hakim-learning-flutter',
    storageBucket: 'hakim-learning-flutter.appspot.com',
    iosBundleId: 'com.example.learningDart',
  );
}
